import { Inter } from "next/font/google";
import '../../styles/fonts.css'
import "./globals.css";
import '@fontsource-variable/league-spartan';
import '@fontsource/aileron';
// Supports weights 100-900
import '@fontsource-variable/montserrat';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body>
      
        {children}
     
        </body>
      
    </html>
  );
}
